"""Task prompts used by the public SAGE-Path reference implementation.

The task-specific prompts below are transcribed from Supplementary Table 3
of the accompanying manuscript. Benchmark, sensitivity-analysis, and
evaluation prompts are intentionally excluded.
"""

PROMPTS = {'translation': 'Please translate the following Chinese pathological report into English '
                'word-for-word without adding any interpretation, explanation, or formatting '
                'changes. Do not polish or paraphrase the text. Do not add any professional '
                'terminology beyond what appears in the original. Keep the original format, '
                'punctuation, and structure exactly the same. Translate (−) and (+) using '
                '“negative” and “positive” respectively. Your translation should be simple, '
                "faithful, and literal, only converting Chinese to English: {case['report']}",
 'rare_tumor_inference': 'You are tasked with making a differential diagnosis based on the '
                         'provided pathology report. Please read the details of the pathology '
                         'report (which may include macroscopic findings, microscopic findings, '
                         'and immunohistochemical results) and determine the most likely tumor '
                         'type.\n'
                         '\n'
                         'Input:\n'
                         'Pathology Report: {report}\n'
                         '\n'
                         'Relevant WHO Clinical Guideline ordered by relevance:\n'
                         '{who_guideline_content}\n'
                         '\n'
                         'Task: Based on the pathology report, identify the most likely tumor '
                         'type. Then provide a brief reasoning (1-2 sentences) explaining why this '
                         'diagnosis is most consistent with the findings in the report.\n'
                         '\n'
                         'Respond in the following format:\n'
                         'Diagnosis: [Most likely tumor type, response the disease name in '
                         'Chinese]\n'
                         'Reasoning: [Concise explanation of how the findings support this '
                         'diagnosis]',
 'rare_tumor_reflection': 'You are tasked with evaluating the quality of a diagnosis made by the '
                          "model. Given the pathology report, the model's diagnosis, and the "
                          "model's reasoning, you need to determine whether the diagnosis is "
                          'reasonable and consistent with the findings in the report.\n'
                          '\n'
                          'Please ensure that you refer to standard pathology guidelines and '
                          'consider the following:    \n'
                          '- Focus on the **overall diagnosis** rather than minor details. The '
                          'diagnosis should be consistent with the major findings in the report, '
                          'including tumor location, morphology, and immunohistochemical markers. '
                          'If the general diagnosis is reasonable, minor issues in reasoning '
                          'should not disqualify it.\n'
                          "- **Consider the tumor's primary site**: Always take into account the "
                          "tumor's location and whether the diagnosis is consistent with common "
                          'tumor types for that location. Tumors in different anatomical sites '
                          'have characteristic types and behavior.\n'
                          '- **Account for prior treatments**: If the report indicates this is a '
                          'recurrent tumor or a post-treatment case, the diagnosis should consider '
                          'how previous treatments (e.g., radiation, chemotherapy) might influence '
                          "the tumor's appearance or behavior.    \n"
                          '- **Be mindful of atypical immunohistochemical findings**: '
                          'Occasionally, tumors may show atypical or unexpected '
                          'immunohistochemical staining. While such findings might seem '
                          'inconsistent with a particular tumor type, they should not '
                          'automatically rule out a diagnosis. Consider the overall pattern of the '
                          'tumor, including its morphology, location, and the immunohistochemical '
                          'profile.\n'
                          '- **Do not base the diagnosis solely on the prevalence of a particular '
                          'tumor type** in the given anatomical location. While some tumors are '
                          'more common in certain locations, a comprehensive analysis of '
                          'morphology, immunohistochemistry, and clinical history is necessary to '
                          'make an accurate diagnosis. For example, while some tumor types may be '
                          'more common in certain regions (e.g., gastrointestinal tumors), other '
                          'rarer types should also be considered if the pathology supports '
                          'them.    \n'
                          '- **Use only clinical information from the case**; do not assume new '
                          'findings or introduce external factors not provided in the report.    \n'
                          '- **Use only plain text**. Do not add formatting symbols like `*`, `_`, '
                          'or `**`.\n'
                          '\n'
                          'Input:\n'
                          'Pathology Report: {case_text}\n'
                          'Model Diagnosis: {model_diagnosis}\n'
                          'Model Reasoning: {reasoning_text}\n'
                          '\n'
                          'Task: Evaluate if the diagnosis is correct based on the pathology '
                          'report and reasoning, while ensuring that you reference medical '
                          'guidelines and standards in your evaluation. \n'
                          '\n'
                          'If the diagnosis is reasonable and supported by the findings in the '
                          'report and follows standard pathology guidelines, return "Evaluation: '
                          'pass" with a concise explanation of why the diagnosis is correct. If '
                          'the diagnosis needs improvement, return "Evaluation: NEEDS_IMPROVEMENT" '
                          'along with a 1-2 sentence reasoning explaining why the diagnosis does '
                          'not align with the pathology report or the standard pathology '
                          'guidelines.\n'
                          '\n'
                          'Respond in the following format:\n'
                          '\n'
                          'Evaluation: [PASS or NEEDS_IMPROVEMENT]\n'
                          'Reasoning: [Concise explanation of why the diagnosis is or is not '
                          'reasonable based on the pathology report, reasoning, and medical '
                          'guidelines]',
 'metastatic_primary_site_inference': 'You are tasked with determining the most likely primary '
                                      'cancer origin based on the provided pathological report. '
                                      'Please read the details of the pathology report (which '
                                      'includes macroscopic findings, microscopic findings, and '
                                      'immunohistochemical results) and determin the most likely '
                                      'primary site.\n'
                                      '\n'
                                      'Input:\n'
                                      '\n'
                                      'Metastatic Site: {location}\n'
                                      'Pathology Report:{report}\n'
                                      '\n'
                                      'WHO Clinical Guideline:\n'
                                      '{who_guideline_content}\n'
                                      '\n'
                                      'Task: Based on the pathology report, the metastatic site, '
                                      'and the relevant WHO guidelines, output the most likely '
                                      'primary cancer origin. Include a brief reasoning (1-2 '
                                      'sentences) explaining why this is the most likely primary '
                                      'site. Respond in the following format:\n'
                                      '\n'
                                      'Diagnosis: [Most likely primary site, response the name in '
                                      'Chinese]\n'
                                      'Reasoning: [Concise reasoning explaining the selection '
                                      'based on the report provided.]',
 'metastatic_primary_site_reflection': 'You are a pathology assistant reviewing the model’s '
                                       "prediction of a tumor's primary site based on:\n"
                                       '\n'
                                       '- the pathology report (including morphology and '
                                       'immunohistochemistry),\n'
                                       '- the metastasis location,\n'
                                       '- the model’s diagnosis and reasoning.\n'
                                       '\n'
                                       'Your task is to determine whether the model’s **final '
                                       'diagnosis is reasonable and well-supported**, and whether '
                                       'the reasoning **adequately explains the key findings**.\n'
                                       '\n'
                                       'Focus on these:\n'
                                       '\n'
                                       '1. **Diagnostic Match**:\n'
                                       '   - Does the diagnosis match the overall '
                                       'immunohistochemistry pattern and metastasis route?\n'
                                       '   - Even if the reasoning is not perfect, is the final '
                                       'answer clinically plausible and supported?\n'
                                       '\n'
                                       '2. **Critical Marker Review**:\n'
                                       '   - Has the model correctly interpreted high-specificity '
                                       'markers (e.g., CDX2, GATA3, PAX8, WT1, TTF-1)?\n'
                                       '   - Are there any *strongly contradictory markers* that '
                                       'were ignored?\n'
                                       '\n'
                                       '3. **Alternative Exclusion (only when applicable)**:\n'
                                       '   - If there is **another diagnosis clearly better '
                                       'supported** by the evidence, and the model failed to '
                                       'consider it, mark as NEEDS_IMPROVEMENT.\n'
                                       '   - Do not penalize the model for not listing every '
                                       'possible alternative unless a more likely one was '
                                       'overlooked.\n'
                                       '\n'
                                       '4. **Granularity Check**:\n'
                                       '   - Is the predicted site too specific (e.g., "sigmoid '
                                       'colon" vs "colorectal")? If so, suggest generalization '
                                       'unless well-justified.\n'
                                       '\n'
                                       'Input:\n'
                                       'Pathology Report: {case_text}\n'
                                       'Metastasis location: {metastasis_location}\n'
                                       'Model Diagnosis: {model_diagnosis}\n'
                                       'Model Reasoning: {reasoning_text}\n'
                                       '\n'
                                       'If the diagnosis is well-aligned with the evidence and '
                                       'there are no major conflicts, even if the reasoning is not '
                                       'comprehensive, respond:\n'
                                       '\n'
                                       'Evaluation: PASS  \n'
                                       'Reasoning: [Succinct reason why the diagnosis is '
                                       'acceptable and supported.]\n'
                                       '\n'
                                       'If the diagnosis contradicts key findings, ignores a '
                                       'clearly better-supported alternative, or over-interprets '
                                       'limited data, respond:\n'
                                       '\n'
                                       'Evaluation: NEEDS_IMPROVEMENT  \n'
                                       'Reasoning: [Explain what the model overlooked, '
                                       'misinterpreted, or where the reasoning failed.]\n'
                                       '\n'
                                       'Respond in the following format:  \n'
                                       'Evaluation: [PASS or NEEDS_IMPROVEMENT]  \n'
                                       'Reasoning: [Concise explanation of the evaluation]',
 'complex_pathology_inference': 'You are tasked with analyzing the following pathology report to:\n'
                                '\n'
                                '1. Make a pathological diagnosis;\n'
                                '2. Assess whether further molecular or genetic testing is '
                                'needed.\n'
                                '\n'
                                'You will be provided with:\n'
                                '- A pathology report including histological and '
                                'immunohistochemical (IHC) findings;\n'
                                '- Optional relevant clinical guidelines or consensus '
                                'recommendations retrieved from expert resources (e.g., WHO, NCCN, '
                                'ESMO).\n'
                                '\n'
                                'Please:\n'
                                '- Read the pathology report carefully;\n'
                                '- If guidelines are provided, you may incorporate them into your '
                                'clinical reasoning;\n'
                                '- Determine the most likely diagnosis and explain your '
                                'reasoning;\n'
                                '- Decide whether further testing (e.g., FISH, NGS, TCR/BCR '
                                'rearrangement) is necessary. If yes, specify the recommended '
                                'tests and provide a rationale. If not, explain why no further '
                                'testing is needed.\n'
                                '\n'
                                'When answering, please:\n'
                                '- Provide a specific diagnosis (including subtype if '
                                'applicable);\n'
                                '- Include key histological and immunohistochemical (IHC) features '
                                'that support your diagnosis;\n'
                                '- Use Chinese for the disease name in your final diagnosis '
                                'output;\n'
                                '- Clearly state whether further testing is recommended, and '
                                'justify your answer.\n'
                                '\n'
                                'Input:\n'
                                'Pathology Report: {report}\n'
                                'Clinical Guidelines or Expert Recommendations (if available): '
                                '{guideline}\n'
                                '\n'
                                'Please output in the following format:\n'
                                '\n'
                                'Diagnosis: [Most likely tumor type, response the disease name in '
                                'Chinese]\n'
                                'Reasoning: [Concise explanation of how the histologic and IHC '
                                'findings support this diagnosis]\n'
                                'Follow up recommendation: [List of tests to be performed in '
                                'English or Chinese; use "None" if no test is recommended]\n'
                                'Rationale: [Concise explanation of why further testing is or is '
                                'not necessary]\n'
                                '\n'
                                '<plain text only, no Markdown formatting (e.g., **bold**, --- '
                                'lines), no titles, no line breaks>',
 'complex_pathology_reflection': 'You are a pathologist trained in applying diagnostic guidelines '
                                 'such as WHO classification, NCCN, and ESMO.  \n'
                                 'You will evaluate whether the model’s diagnosis and '
                                 'recommendation are **reasonable and justified**, taking into '
                                 'account these guidelines as clinical reference—not as strict '
                                 'rules.  \n'
                                 'Use your expert reasoning to judge whether the model missed any '
                                 'critical diagnostic logic or failed to recommend necessary '
                                 'follow-up based on evidence.\n'
                                 '\n'
                                 'Input:\n'
                                 'Pathology Report: {report}\n'
                                 '\n'
                                 "Model's Diagnosis: {diagnosis}\n"
                                 "Model's Reasoning: {reasoning}\n"
                                 '\n'
                                 "Model's Recommendation: {recommendation}\n"
                                 "Model's Rationale: {rationale}\n"
                                 '\n'
                                 'You must evaluate:\n'
                                 '1. **Diagnosis specificity**:\n'
                                 '- Is the diagnosis precise enough (e.g., includes subtype) based '
                                 'on the IHC and morphology?\n'
                                 '- If the findings support a more specific diagnosis (e.g., '
                                 'pediatric-type FL instead of “follicular lymphoma”), but the '
                                 'model gives only a broad label, mark the diagnosis as '
                                 'incomplete.\n'
                                 '- Is the reasoning consistent and clinically sound?\n'
                                 '\n'
                                 '2. **Recommendation value**:\n'
                                 '- Is the recommendation clinically meaningful?\n'
                                 '- Testing should help confirm a specific subtype, rule out '
                                 'critical mimics, or guide treatment or prognosis (e.g., HER2 for '
                                 'therapy, POLE/MSI for risk, MYC/BCL2 for classification).\n'
                                 '- If the model says “None”, but the case clearly supports '
                                 'next-step testing based on guidelines or ambiguity, the '
                                 'recommendation must be improved.\n'
                                 '\n'
                                 'Evaluation Criteria:\n'
                                 '- **PASS**: If both the diagnosis and the recommendation align '
                                 'with the clinical and pathology guidelines, and the reasoning is '
                                 'sound and justified.\n'
                                 '- **NEEDS_IMPROVEMENT**:\n'
                                 '    - If the diagnosis does not match the clinical and '
                                 'pathological findings (e.g., incorrect tumor type or subtype), '
                                 'the feedback should indicate that the **diagnosis** did not '
                                 'pass.\n'
                                 '    - If the diagnosis is correct but the recommendation '
                                 'incorrect (i.e., not based on clinical evidence or guidelines) '
                                 'or not enought, the feedback should indicate that the '
                                 '**recommendation** did not pass.\n'
                                 '\n'
                                 'Output format (strictly follow this structure):\n'
                                 'Evaluation: [PASS or NEEDS_IMPROVEMENT]\n'
                                 'ModuleWithError: [Output "Diagnosis" if the diagnosis is flawed, '
                                 'incomplete, or unsupported, regardless of whether the '
                                 'recommendation is acceptable;\n'
                                 '    Output "Recommendation" if the diagnosis is acceptable but '
                                 'the suggested follow-up testing is missing, incorrect, or '
                                 'misaligned with clinical logic;\n'
                                 '    Output "Both" if both diagnosis and recommendation are '
                                 'incorrect, incomplete, or inconsistent with evidence or '
                                 'guidelines;\n'
                                 '    Output \'None\' if PASS — only choose from "Diagnosis", '
                                 '"Recommendation", or "Both"]\n'
                                 'Reasoning: [If ModuleWithError is "Diagnosis", focus only on '
                                 'diagnostic issues (e.g., unsupported reasoning, missing key IHC '
                                 'features, misclassification).\n'
                                 '                            If "Recommendation", only discuss '
                                 'flaws in follow-up testing (e.g., missing necessary molecular '
                                 'tests, redundant suggestions).\n'
                                 '                            If "Both", explain both problems '
                                 'clearly in a single sentence.\n'
                                 '                            If "None", briefly confirm both '
                                 'diagnosis and recommendation are medically justified.]\n'
                                 '\n'
                                 'Constraints:\n'
                                 '- Only output one evaluation line and one reasoning line.\n'
                                 '- Do not use Markdown formatting, no bullet points, no line '
                                 'breaks within a field.\n'
                                 '- Be specific but concise.'}

TASKS = {
    "rare_tumor": {
        "inference_prompt": PROMPTS["rare_tumor_inference"],
        "reflection_prompt": PROMPTS["rare_tumor_reflection"],
        "retrieval_instruction": (
            "Based on the pathology report and immunohistochemical findings, "
            "determine the most likely tumour type."
        ),
        "required_fields": (),
    },
    "metastatic_primary_site": {
        "inference_prompt": PROMPTS["metastatic_primary_site_inference"],
        "reflection_prompt": PROMPTS["metastatic_primary_site_reflection"],
        "retrieval_instruction": (
            "Based on the metastatic-site pathology report and immunohistochemical "
            "findings, determine the most likely primary cancer origin."
        ),
        "required_fields": ("location",),
    },
    "complex_pathology": {
        "inference_prompt": PROMPTS["complex_pathology_inference"],
        "reflection_prompt": PROMPTS["complex_pathology_reflection"],
        "retrieval_instruction": (
            "Determine the most likely diagnosis and whether additional molecular or "
            "genetic testing is indicated."
        ),
        "required_fields": (),
    },
}

SUPPORTED_TASKS = tuple(TASKS)
